---
- name: shedule at task
  hosts: webservers
  become: true
  become_user: rasul
  tasks:
    - name: create at task
      at:
        command: "date > ~/my_at_date_time\n"
        count: 1
        units: minutes
        unique: yes
        state: present
