---
- name: crate crontab
  hosts: webservers
  become: true
  tasks:
    - name: add date and file to a file
      cron:
        name: my_date_time_cron_job
        minute: "*/2"
        hour: 9-16
        weekday: 1-5
        user: rasul
        job: date >> /home/rasul/my_date_time_cron_job
        cron_file: add-date-time
        state: absent
