---
- name: setting default boot target
  hosts: webservers
  become: true
  tasks:
    - name: change default boot
      file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
