---
- name: (Debian 9) Add backports repo for Redis 5
  apt_repository:
    repo: "deb http://ftp.debian.org/debian stretch-backports main"
    state: present
    filename: "stretch-backports"
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '9'

- name: (Debian 9) Install Redis from backports
  package:
    name: "{{ redis_packages }}"
    default_release: stretch-backports
    state: present
  register: redis_installed
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '9'

- name: (Ubuntu) Update APT cache
  apt:
    force_apt_get: true
    update_cache: true
    cache_valid_time: "3600"
    state: present
  when: ansible_distribution == 'Ubuntu'
