---
# tasks file for inmotion.redis

- name: (Redis) Include os_family vars
  include_vars: "{{ ansible_os_family }}.yml"
  vars:
    targets:
      - Debian
  when: ansible_os_family in targets

- name: (Redis) Include os_family tasks
  include: '{{ ansible_os_family }}.yml'
  vars:
    targets:
      - Debian
      - RedHat
  when: ansible_os_family in targets

- name: (Redis) Install Redis if not yet performed
  package:
    name: "{{ redis_packages }}"
    state: present
  when: not redis_installed.changed

- name: (Redis) Get Redis version
  register: redis_installed_version
  shell: |
    set -o pipefail
    redis-server --version | awk '{print $3}' | sed 's/v=//'
  args:
    executable: /bin/bash
  changed_when: false

- name: (Redis) Set Redis version as fact
  set_fact:
    redis_version: '{{ redis_installed_version.stdout_lines[0] }}'

- name: (Redis) Configure Redis
  template:
    src: redis.conf.j2
    dest: '{{ redis_conf }}'
    owner: root
    group: root
    mode: '0644'

- name: Include systemd restart configuation
  include: systemd.yml
  when:  >-
    ( redis_systemd_restart|default(False)
    or systemd_restart|default(False) )
    and systemd_restart_setting is defined

- name: (Redis) Enable and start redis service
  service:
    name: '{{ redis_daemon }}'
    state: started
    enabled: true
