---
- name: create user account
  hosts: webservers
  become: true
  remote_user: rasul
  vars_files:
    - secret.yml
  tasks:

    - name: create user from secret
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"
