---
- name: Time synchronization
  hosts: webservers
  become: true
  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name: set timezone
      timezone:
        name: "{{ host_timezone }}"
      notify: restart crond

  handlers:
    - name: restart crond
      service: 
        name: chronyd
        state: restarted
