---
# tasks file for myvhost
- name: httpd installed
  yum:
    name: httpd
    state: latest

- name: httpd started
  service:
    name: httpd
    state: started
    enabled: true

- name: copy template
  template:
    src: vhost.conf.j2 
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: 
    - restart httpd
