---
- name: configure SOE
  hosts: 'webservers'
  become: true
  vars:
    - system_owner: rasul@example.com
  tasks:
    - name: copying template
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
